import React, { useCallback } from 'react';
import {
  ReactFlow,
  MiniMap,
  Controls,
  Background,
  useNodesState,
  useEdgesState,
  addEdge,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';

// Customizing the look of the map
const nodeStyles = {
  background: '#fff',
  color: '#1e293b',
  border: '1px solid #e2e8f0',
  borderRadius: '12px',
  padding: '10px',
  fontSize: '12px',
  fontWeight: 'bold',
  width: 150,
  textAlign: 'center',
  boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
};

const MindMap = ({ data }) => {
  // data expected: { nodes: [], edges: [] } generated by Gemini
  const [nodes, setNodes, onNodesChange] = useNodesState(data?.nodes || []);
  const [edges, setEdges, onEdgesChange] = useEdgesState(data?.edges || []);

  const onConnect = useCallback(
    (params) => setEdges((eds) => addEdge(params, eds)),
    [setEdges]
  );

  return (
    <div className="w-full h-full bg-slate-50">
      <ReactFlow
        nodes={nodes.map(node => ({ ...node, style: nodeStyles }))}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        fitView
      >
        <Controls />
        <MiniMap zoomable pannable />
        <Background color="#cbd5e1" gap={20} />
      </ReactFlow>
      
      {/* Visual Overlay for User Guidance */}
      <div className="absolute bottom-4 left-4 z-10 bg-white/80 backdrop-blur-md p-3 rounded-lg border border-slate-200 text-[10px] font-bold text-slate-500 uppercase tracking-widest">
        Interactive Concept Graph
      </div>
    </div>
  );
};

export default MindMap;